<a href="https://colab.research.google.com/github/zfukuoka/Copying_a_sutra/blob/master/ISBN978-4-7981-6720-6/list5_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5 ディープラーニングの理論

* 5.5 行列と行列積

### リスト 5.15 NumPyを用いた要素ごとの積の計算

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[0, 1, 1],
              [1, 0, 1],
              [1, 1, 0]])
print(a*b)

[[0 2 3]
 [4 0 6]
 [7 8 0]]
