<a href="https://colab.research.google.com/github/zfukuoka/Copying_a_sutra/blob/master/ISBN978-4-7981-6720-6/list4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# リスト 4.1 Irisデータセットを読み込む

In [ ]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
print(iris.data[:10])
print(iris.data.shape)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# リスト 4.2 データを前処理する

In [ ]:
from sklearn import preprocessing
from keras.utils import np_utils

# ---- 入力データ ----
scaler = preprocessing.StandardScaler()
scaler.fit(iris.data)
x = scaler.transform(iris.data)
print(x[:10])

# ---- 正解データ ----
t = np_utils.to_categorical(iris.target)
print(t[:10])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


# リスト 4.3 データを訓練用データとテスト用データに分割する

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, t_train, t_test = train_test_split(x, t, train_size=0.75)

# リスト 4.4 Kerasでモデルを構築する

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_dim=4))
model.add(Activation('relu'))
model.add(Dense(3))
model.add(Activation('softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 32)                160       
                                                                 
 activation_6 (Activation)   (None, 32)                0         
                                                                 
 dense_7 (Dense)             (None, 3)                 99        
                                                                 
 activation_7 (Activation)   (None, 3)                 0         
                                                                 
Total params: 259
Trainable params: 259
Non-trainable params: 0
_________________________________________________________________
None


# リスト 4.5 モデルを訓練する

In [8]:
history = model.fit(x_train, t_train, epochs=30, batch_size=8)

Epoch 1/30
14/14 [==============================] - 1s 2ms/step - loss: 1.2687 - accuracy: 0.2946
Epoch 2/30
14/14 [==============================] - 0s 1ms/step - loss: 1.1234 - accuracy: 0.3393
Epoch 3/30
14/14 [==============================] - 0s 1ms/step - loss: 1.0092 - accuracy: 0.4196
Epoch 4/30
14/14 [==============================] - 0s 1ms/step - loss: 0.9180 - accuracy: 0.5714
Epoch 5/30
14/14 [==============================] - 0s 1ms/step - loss: 0.8430 - accuracy: 0.7589
Epoch 6/30
14/14 [==============================] - 0s 1ms/step - loss: 0.7805 - accuracy: 0.8214
Epoch 7/30
14/14 [==============================] - 0s 1ms/step - loss: 0.7267 - accuracy: 0.8482
Epoch 8/30
14/14 [==============================] - 0s 1ms/step - loss: 0.6802 - accuracy: 0.8750
Epoch 9/30
14/14 [==============================] - 0s 1ms/step - loss: 0.6409 - accuracy: 0.8661
Epoch 10/30
14/14 [==============================] - 0s 1ms/step - loss: 0.6064 - accuracy: 0.8661
Epoch 11/30
14/14 [