<a href="https://colab.research.google.com/github/zfukuoka/Copying_a_sutra/blob/master/ISBN978-4-7981-6720-6/list5_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5 ディープラーニングの理論

* 5.5 行列と行列積

### リスト 5.13 NumPyをつかって行列を表す

In [1]:
import numpy as np
a = np.array([[1, 0, 5],
              [4, 3, 2]])
print(a)

b = np.array([[1.2, 0.18],
              [2.3, -0.31],
              [0.42, -4.5]])
print(b)

[[1 0 5]
 [4 3 2]]
[[ 1.2   0.18]
 [ 2.3  -0.31]
 [ 0.42 -4.5 ]]
